#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}' /etc/nginx/sites-available/default
service nginx restart
