#!/usr/bin/env bash
# Configure the nginx serveur
# shellcheck disable=SC2154,SC2016
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}' /etc/nginx/sites-available/default
cat 404.html > /var/www/html/404.html
sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
