#!/usr/bin/env bash
# Configure the nginx serveur
apt-get update
apt-get -y install nginx
sed -i '/server_name _;/a \\tadd_header X-Served-By ${HOSTNAME};' /etc/nginx/sites-available/default
service nginx restart
