#!/usr/bin/env bash
# Recreate symbolic link & restart nginx
pkill -9 nginx
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
