#!/usr/bin/env bash
# Manage the file manage_my_process
function error() {
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
}
function start() {
	./manage_my_process
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
}
function restart() {
	pkill -f "./manage_my_process"
	rm -f /var/run/my_process.pid
	./manage_my_process
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
}
function stop() {
	pkill -f "./manage_my_process"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
}
if [ $# -ne 1 ]; then
	error
elif [ $1 = "start" ]; then
	start
elif [ $1 = "restart" ]; then
	restart
elif [ $1 = "stop" ]; then
	stop
else
	error
fi
